repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0 # Use the latest stable version
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/psf/black
    rev: 25.1.0 # Use the latest stable version
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1 # Use the latest stable version
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0 # Use the latest stable version
    hooks:
      - id: flake8
